import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

import { Montserrat } from "next/font/google";
const bodyFont = Montserrat({ 
  subsets: ["latin"],
  weight: ['400'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={bodyFont.className}>
        <div className="max-w-6xl min-h-screen my-0 mx-auto flex flex-col justify-around ">
          <Navbar />
          {children}
          <Footer />
        </div>
        </body>
    </html>
  );
}
